version: "3.3"
services:
  todolist_db:
    container_name: todolist_db
    hostname: todolist_db
    image: postgres:12
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/data/postgres
    volumes:
      - "./db/data:/data/postgres"
    restart: unless-stopped
    networks:
      - ie-todolist-network

  todolist_java:
    depends_on:
      - todolist_db
    container_name: todolist_java
    image: openjdk:19
    environment:
      - POSTGRES_SERVER=todolist_db
      - POSTGRES_PORT=5432
      - API_PORT=3300
    volumes:
      - "./api/target:/usr/src/myapp"
    ports:
      - "3300:3300"
    # restart: unless-stopped
    command: "java -jar /usr/src/myapp/api-1.0.1.war"
    networks:
      - ie-todolist-network

  todolist_httpd:
    container_name: todolist_httpd
    image: httpd:2.4
    env_file:
      - ./.env
      - ./.env.example
    volumes:
      - "./client/stage:/usr/local/apache2/htdocs/"
      - "./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf"
    restart: unless-stopped
    networks:
      - ie-todolist-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  todolist_nginx:
    depends_on:
      - todolist_httpd
    container_name: todolist_nginx
    image: nginx
    env_file:
      - ./.env
      - ./.env.example
    volumes:
      - "./nginx/webdev.conf:/etc/nginx/conf.d/default.conf"
      # - "./client/build:/var/www/html"
    ports:
      - "${WEB_PORT}:80"
    restart: unless-stopped
    networks:
      - ie-todolist-network

networks:
  ie-todolist-network:
