version: "3.3"
services:
  todolist_db:
    container_name: todolist_db
    hostname: todolist_db
    image: postgres
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/data/postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - "./db/data:/data/postgres"
    restart: unless-stopped
    networks:
      - ie-todolist-network

  todolist_httpd:
    container_name: todolist_httpd
    image: httpd:2.4
    env_file:
      - ./.env
      - ./.env.example
    volumes:
      - "./client/public/.htaccess.webdev:/usr/local/apache2/htdocs/.htaccess"
      - "./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf"
    restart: unless-stopped
    networks:
      - ie-todolist-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  todolist_nginx:
    depends_on:
      - todolist_httpd
    container_name: todolist_nginx
    image: nginx
    env_file:
      - ./.env
      - ./.env.example
    volumes:
      - "./nginx/webdev+apidev.conf:/etc/nginx/conf.d/default.conf"
      # - "./client/build:/var/www/html"
    ports:
      - "${WEB_PORT}:80"
    restart: unless-stopped
    networks:
      - ie-todolist-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  ie-todolist-network:
