version: "3.3"
services:
  todolist_db:
    container_name: todolist-postgres
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/data/postgres
    volumes:
      - "./db/data:/data/postgres"
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
    env_file:
      - ./.env
    networks:
      - ie-todolist-network

  todolist-tomcat-mysql:
    container_name: todolist-tomcat-mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file: ./.env
    # environment:
    #   - MYSQL_ROOT_PASSWORD=root
    #   - MYSQL_DATABASE=testdb1
    #   - MYSQL_PORT=3306
    #   - MYSQL_USER=testuser
    #   - MYSQL_PASSWORD=root
    networks:
      - ie-todolist-network

  todolist-tomcat-phpmyadmin:
    container_name: todolist-tomcat-phpmyadmin
    depends_on:
      - todolist-tomcat-mysql
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    env_file: ./.env
    # environment:
    #   - PMA_HOST=todolist-tomcat-mysql
    #   - MYSQL_PORT=3306
    #   - MYSQL_ROOT_PASSWORD=root
    networks:
      - ie-todolist-network

  todolist_tomcat:
    depends_on:
      - todolist-tomcat-mysql
      - todolist_db
      - todolist-tomcat-phpmyadmin
    container_name: todolist-tomcat
    image: tomcat:10-jdk21-openjdk
    volumes:
      - "./tomcat/:/usr/local/tomcat/webapps/"
    ports:
      - "${TOMCAT_PORT}:8080"
      - "${API_PORT}:${API_PORT}"
    env_file: ./.env
    # environment:
    #   - MYSQL_ROOT_PASSWORD=root
    #   - MYSQL_DATABASE=testdb1
    #   - MYSQL_PORT=3306
    #   - MYSQL_USER=testuser
    #   - MYSQL_PASSWORD=root
    networks:
      - ie-todolist-network

networks:
  ie-todolist-network:
