version: "3"

services:
  todolistdb:
    container_name: postgres-todolist
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - "./data:/data/postgres"
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_todolist
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@todolist.ie
      PGADMIN_DEFAULT_PASSWORD: pgadminpassword
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data: